apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gitleaks
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.28.0"
    tekton.dev/categories: Security Tools
    tekton.dev/tags: security-tool
    tekton.dev/displayName: "Code forgotten secrets scan"
spec:
  description: |
    This task scan source code for secrets leak
  steps:
  - name: scan
    image: zricethezav/gitleaks:v8.0.0
    workingDir: $(workspaces.source.path)
    script: |
      gitleaks detect --source="$(workspaces.source.path)" -v
  workspaces:
    - name: source
      description: Source code workspace 
