apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: books-trigger-template
spec:
  params:
  - name: git_url
    description: git repository URL.
  - name: git_commit
    description: Git commit.
  - name: chart_repo_url
    description: URL for helm charts repository.
  - name: chart_name
    description: Helm chart name.
  - name: chart_version
    description: Helm chart version.
  - name: release      
    description: Helm release name.
  - name: description
    description: Helm installation description.
  - name: namespace
    description: Namespace to deploy application.
  - name: helm_custom_file
    description: Helm custom config file.
  - name: image_repo
    description: "Image repository (Ex: gcr.io/project123/myimage)."
  - name: image_tag
    description: Image tag   
  - name: enable_notifications
    description: Slack notifications should be enabled? ("true"|"false").
  - name: git_repo
    description: Git repository full name.
  - name: git_branch
    description: Git branch.
  - name: pusher_name
    description: Git pusher name. 
  - name: pusher_email
    description: Git pusher email.
  - name: recipients
    description: Recipient email address list separated by space or a group.


  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: books-golang-pipeline-run-
    spec:
      serviceAccountName: tekton-triggers    
      pipelineRef:
        name: golang-pipeline
      params:
      - name: git_url
        value: $(tt.params.git_url)
      - name: git_commit
        value: $(tt.params.git_commit)        
      - name: chart_repo_url
        value: $(tt.params.chart_repo_url)
      - name: chart_name
        value: $(tt.params.chart_name)      
      - name: chart_version
        value: $(tt.params.chart_version)     
      - name: release
        value: $(tt.params.release) 
      - name: description
        value: $(tt.params.description)         
      - name: namespace
        value: $(tt.params.namespace) 
      - name: helm_custom_file
        value: $(tt.params.helm_custom_file)    
      - name: image_repo
        value: $(tt.params.image_repo)
      - name: image_tag 
        value: $(tt.params.image_tag)    
      - name: enable_notifications
        value: $(tt.params.enable_notifications) 
      - name: git_repo
        value: $(tt.params.git_repo)
      - name: git_branch
        value: $(tt.params.git_branch)
      - name: pusher_name
        value: $(tt.params.pusher_name)
      - name: pusher_email
        value: $(tt.params.pusher_email)
      - name: recipients
        value: $(tt.params.recipients)  


      workspaces:
      - name: github-ssh
        secret:
          secretName: github-ssh
      - name: code-ws
        persistentVolumeClaim:
          claimName: books-pipeline
      
      

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: books-trigger-binding
spec:
  params:
  - name: git_url
    value: $(body.repository.ssh_url)
  - name: git_commit
    value: $(body.after)
  - name: chart_repo_url
    value: https://antonio-tolentino.github.io/charts/
  - name: chart_name
    value: generic
  - name: chart_version
    value: "1.1.0"   
  - name: release
    value: books
  - name: description
    value: "commit $(body.after)"
  - name: namespace
    value: tekton-tests
  - name: helm_custom_file
    value: helm.yaml
  - name: image_repo
    value: tolentino/books
  - name: image_tag 
    value: $(extensions.short_sha)
  - name: enable_notifications
    value: "true"
  - name: channel
    value: tekton-pipelines
  - name: git_repo
    value: $(body.repository.full_name)
  - name: git_branch
    value: $(extensions.branch_name)
  - name: pusher_name
    value: $(body.pusher.name)
  - name: pusher_email
    value: $(body.pusher.email)
  - name: recipients
    value: atcjunior@gmail.com